Repository arb/celebrate, pull requests merged in 2019-11, with the labels that each got.

#137 Update errors() typedef
  lib/index.d.ts
Labels: types

#136 Joi@16 Updates
  lib/constants.js
  lib/index.js
  lib/schema.js
  package-lock.json
  package.json
  test/__snapshots__/celebrate.test.js.snap
  test/celebrate.test.js
  test/integration.test.js
  utils/benchmark.js
Labels: breaking-change

#140 Update format + exposes Segments
  README.md
  lib/constants.js
  lib/index.d.ts
  lib/index.js
  package-lock.json
  package.json
  test/__snapshots__/celebrate.test.js.snap
  test/celebrate.test.js
  test/integration.test.js
Labels: breaking-change

#144 Use CelebrateError object instead of POJO
  README.md
  lib/index.d.ts
  lib/index.js
  test/__snapshots__/celebrate.test.js.snap
  test/celebrate.test.js
Labels: breaking-change

#148 Per request `steps`
  lib/index.js
  test/integration.test.js
Labels: bug
