Repository arb/celebrate, pull requests merged in 2020-09, with the labels that each got.

#185 Full Validate Implementation
  README.md
  lib/CelebrateError.js
  lib/celebrate.js
  lib/constants.js
  lib/index.d.ts
  lib/index.js
  lib/schema.js
  test/__snapshots__/celebrate.test.js.snap
  test/celebrate.test.js
  utils/benchmark.js
Labels: breaking-change, enhancement

#190 Move away from @hapi/joi
  lib/celebrate.js
  lib/index.d.ts
  lib/index.js
  lib/schema.js
  package.json
  test/__snapshots__/celebrate.test.js.snap
Labels: breaking-change, dependency

#195 Make isCelebrateError a type guard
  lib/index.d.ts
Labels: types
